import os
from dotenv import load_dotenv

load_dotenv()

FARAZSMS_API_KEY = os.getenv("FARAZSMS_API_KEY", "")
FARAZSMS_LINE_NUMBER = os.getenv("FARAZSMS_LINE_NUMBER", "")
FARAZSMS_WELCOME_PATTERN_CODE = os.getenv("FARAZSMS_WELCOME_PATTERN_CODE", "")
FARAZSMS_REFERRAL_PATTERN_CODE = os.getenv("FARAZSMS_REFERRAL_PATTERN_CODE", "")
ADMIN_PASSWORD = os.getenv("ADMIN_PASSWORD", "admin123")
DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./referral.db")
DEFAULT_REFERRER_DISCOUNT = int(os.getenv("DEFAULT_REFERRER_DISCOUNT", "50000"))
DEFAULT_REFERRED_DISCOUNT = int(os.getenv("DEFAULT_REFERRED_DISCOUNT", "30000"))
